<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '7.7.1.2',
  'acceptable_sugar_versions' => 
  array (
    0 => '',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'PRO',
    1 => 'CORP',
    2 => 'ENT',
    3 => 'ULT',
  ),
  'readme' => '',
  'key' => 'uni',
  'author' => 'Ateeq',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Uni',
  'published_date' => '2017-07-21 10:27:44',
  'type' => 'module',
  'version' => 1500632864,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Uni',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'uni_Class',
      'class' => 'uni_Class',
      'path' => 'modules/uni_Class/uni_Class.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'uni_Student',
      'class' => 'uni_Student',
      'path' => 'modules/uni_Student/uni_Student.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'uni_Course',
      'class' => 'uni_Course',
      'path' => 'modules/uni_Course/uni_Course.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
  ),
  'relationships' => 
  array (
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/uni_Class',
      'to' => 'modules/uni_Class',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/uni_Student',
      'to' => 'modules/uni_Student',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/uni_Course',
      'to' => 'modules/uni_Course',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
);